# SPDX-FileCopyrightText: 2026 libarchive_oxide contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Bulk annotations for files without inline SPDX headers.

version = 1

[[annotations]]
path = [
  "**/*.md",
  "Cargo.lock",
  ".gitignore",
  "fuzz/.gitignore",
  ".github/CODEOWNERS",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 libarchive_oxide contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["fuzz/corpus/**"]
precedence = "override"
SPDX-FileCopyrightText = "2026 libarchive_oxide contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"
