# SPDX-FileCopyrightText: 2026 libarchive_oxide contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
rust-version.workspace = true
publish = false
license.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
libarchive_oxide-core = { path = "../libarchive_oxide-core" }

[lints]
workspace = true
